config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, 
  # see https://guides.rubyonrails.org/routing.html
  
  #read
  get 'tasks', to: 'tasks#index'  
  get 'tasks/:id', to: 'tasks#show', as: :task

  #create
  get 'tasks/new:', to: 'tasks#new' 
  post 'tasks', to: 'tasks#create' 

  #update
  get 'tasks/:id/edit', to: 'tasks#edit' 
  patch 'tasks/:id', to: 'tasks#update'

  #delete
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = Task.all
    end

    def show
        @task = Task.find(params[:id])
    end

    def new
        
    end

    def create
    end

    def edit
    end

    def update
    end

    def destroy
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_controllers_helper.rb
module TaskControllersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager Patty y Tabita</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Nuestros Task</h1>

<% @tasks.each do |task| %>
  <h2><% task.title%> <small><%=task.details%></small></h2>
  <%= link_to "Mas Detalles", task_path(task) %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %><%= @task.details %></h1>
<p><%= %>
<% %>
<%= link_to "Volver al listado", tasks_path %>